on: 
  pull_request:
    branches:
      - main


stages:
- stage: 'Terraform_Plan'
  displayName: 'Terraform Plan'
  jobs:
  - job: 'Terraform_Plan'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: TerraformCLI@0
      displayName: 'terraform plan'
      inputs:
        command: plan
        environmentServiceName: 'My Azure Service Connection'

