name: 'Terraform Plan'

on:
  pull_request:
    branches:
    - main

jobs:
  terraform-plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init Dev
      run: terraform init -backend-config="envs/dev/backend.conf" 

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Plan Dev
      id: tf-plan
      run: terraform plan -var-file="envs/dev/dev.tfvars" 
